name: ci

on:
  push:
    branches:
      - 'main'
      - 'dev'
jobs:

  build-and-push-image-dev:
    runs-on: ubuntu-latest
    steps:
      # Custom steps for the 'dev' branch
      - name: Build the image on the local computer
        run:  docker buildx build -o type=docker,dest=- . > k8s-fastapi:0.0.3.tar
  
  build-and-push-image-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MYGITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/uberbalogun/k8s-fastapi:0.0.3
